# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
